### ISSUE TITLE
Setting DEBUG_LEVEL to 1 results in compile errors

### ISSUE THREAD

**Issue by jonemo** [sparkfun/WiFly-Shield#26]
Setting 
```c
   #define DEBUG_LEVEL 1
```
results in this compile error for every location where a variable is passed as second parameter to DEBUG_LOG(): 
```
C:\Users\Jonas\Desktop\arduino-1.0.4\libraries\WiFly\WiFlyDevice.cpp:51: error: initializer fails to determine size of '__c'
```

**Comment by ToniCorinne** [comment]
For anyone still looking for support on this product, we have moved this library to [here](https://github.com/sparkfun/SparkFun_WiFly_Shield_Arduino_Library), and have modified the code.
