### ISSUE TITLE
Doesn't seem to be working with Arduino mega ATmega1280

### ISSUE THREAD

**Issue by chaitanyagurrapu** [sparkfun/WiFly-Shield#35]
Hi,

I tried the fork of the library that is meant to get the WiFly shield working with the Mega here https://github.com/jmr13031/WiFly-Shield (since I can't raise issues over there, I am doing it here).

I have upgraded my Arudino IDE and rewired the pins as suggested here http://mcukits.com/2009/04/06/arduino-ethernet-shield-mega-hack/

But the shield still hangs at when trying to call  `WiFly.begin();` Basically I couldn't get the forked code to work with IDE 1.02.

But when I downgraded my IDE to "Arduino 022" and got the original code from http://sparkfun.com/Code/wifly/WiFly-20100519-023939.zip , it seems to be working fine. That rules out any hardware issues. (After I changed the pin mappings in spi.h. See my original travels with this stack here http://electronics.stackexchange.com/questions/3273/arduino-mega-and-wifly-shield )

Has anyone been able to successfully get the version of the shield here https://www.sparkfun.com/products/9954 (I believe it my be version 2) working with the Arduino IDE 1?

**Comment by ToniCorinne** [comment]
For anyone still looking for support on this product, we have moved this library to [here](https://github.com/sparkfun/SparkFun_WiFly_Shield_Arduino_Library), and have modified the code.
