### ISSUE TITLE
conflict with softSerial

### ISSUE THREAD

**Issue by chrisTactition** [sparkfun/WiFly-Shield#36]
I encountered an issue this week where softSerial (based on newSoftSerial) does not work in a project that also uses SpiSerial. The order of the include files makes a difference, and both seem to work if softserial.h is included first.

**Comment by ToniCorinne** [comment]
Thank you for documenting this fix!

For anyone still looking for support on this product, we have moved this library to [here](https://github.com/sparkfun/SparkFun_WiFly_Shield_Arduino_Library), and have modified the code.
