### ISSUE TITLE
Web Client only working with the example file

### ISSUE THREAD

**Issue by thelostscientist** [sparkfun/WiFly-Shield#38]
Hi,

This is my code and I cannot get it work; any Help?

#include <SPI.h>
#include <WiFly.h>

#include "Credentials.h"

String request = "GET /api/emotions/primary/totals HTTP/1.1";
String host = "wefeel.csiro.au";
char msg[128];
int lettercount = 0;
byte server[] = { 54, 84, 79, 112 }; // WeFeel

WiFlyClient client("54.84.79.112", 80);

void setup() {
  
  Serial.begin(9600);

  WiFly.begin();
  
  if (!WiFly.join(ssid, passphrase)) {
    Serial.println("Association failed.");
    while (1) {
      // Hang on failure.
    }
  }  

  Serial.println("connecting...");
delay(25000);
  if (client.connect()) {
    char c;
    int dataFlag = 0;
    int msgIsolator = 0;
    Serial.println("connected");
    Serial.println(request);
    delay(25000);
    client.println(request);
    client.println("\r\n");
    client.println(host);
    client.println("\r\n\r\n");
    delay(500);    
    client.print(c);
    client.println();
    client.flush();
    client.read();
  } else {
    Serial.println("connection failed");
  }
  
}

void loop() {
  if (client.available()) {
    char c = client.read();
    Serial.print(c);
  }
  
  if (!client.available()) {
    Serial.println();
    Serial.println("disconnecting.");
    client.stop();
    for(;;)
      ;
  }
}

**Comment by ToniCorinne** [comment]
Closing this issue out due to inactivity.

For anyone still looking for support on this product, we have moved this library to [here](https://github.com/sparkfun/SparkFun_WiFly_Shield_Arduino_Library), and have modified the code.
